name: CI

on:
  push:
    branches: [main-hold]
  pull_request:
    branches: [main-hold]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - run: bazel build //...
      - run: bazel test //...
